<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://ericksonlopez.dev/schemas/orders"
           xmlns="https://ericksonlopez.dev/schemas/orders"
           elementFormDefault="qualified">

  <xs:element name="Order">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="OrderId" type="xs:string" />
        <xs:element name="CustomerId" type="xs:string" />
        <xs:element name="OrderDate" type="xs:dateTime" />
        <xs:element name="Items">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Item" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Sku" type="xs:string" />
                    <xs:element name="Quantity">
                      <xs:simpleType>
                        <xs:restriction base="xs:int">
                          <xs:minInclusive value="1" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="UnitPrice">
                      <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                          <xs:minExclusive value="0.00" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>
