# Copyright © Erickson Lopez. MIT License.
codecov:
  require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

ignore:
  - "samples/**/*"
  - "benchmarks/**/*"
  - "tests/**/*"
  - "docs/**/*"
  - "scripts/**/*"
  - "**/*.g.cs"
  - "**/Generated/**"
